---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: Platform Engineering Team
spec:
  type: team
  profile:
    displayName: Platform Team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: stxkxs
  annotations:
    github.com/user-login: stxkxs
spec:
  profile:
    displayName: stxkxs
  memberOf:
    - platform-team
